Mentions/custom emojis/attachments formatting
LuisMayo/ace-attorney-discord-bot pull request #11
Opened 2021-03-27 22:36 UTC by RemedyTwo

Custom emojis and mentions were printed out as they are coded instead of what the end user see. I made changes so that:

1. mentions appear as they do for users ("@username" instead of "@!bunch of numbers")
2. custom emojis are removed from the message, and if a message is empty as a result, it is skipped
3. if a file is attached to a message, it is marked as such (the same way links are mentioned, with "(image)" for images, "(video)" for videos, etc.)

I tried to modify as little as possible to not cause any trouble, and I did some tests to make sure everything's fine, and as far as I know there shouldn't be any problems but some more tests may be necessary.

Video showcase: 
Original:

https://user-images.githubusercontent.com/40474557/112736170-e5c54b00-8f50-11eb-9782-22d774eb999c.mp4

Updated:

https://user-images.githubusercontent.com/40474557/112736172-e827a500-8f50-11eb-9df4-98471998d164.mp4

2021-03-28 18:22 UTC, LuisMayo requested changes
Hi!
Wonderful work, thanks a lot for sharing it
There are a couple issues though

- [ ] Emoji detection doesn't seem to be fully working and emojis are being displayed as unknown characters. Maybe you should apply the emoji detection to the text instead of the clean content? Displaying the :emoji_code: will work too.
- [ ] @everyone and @here mentions are showing strange characters as well

I appreciate your contribution a lot. If you would be as kind as to fix these problems it would be extra nice.

Thanks.

2021-03-30 18:43 UTC, RemedyTwo commented
Okay, so as for @everyone and @here mentions: using clean_content made an invisible character spawn between the '@' and the text for some reason.

As for emojis, I assume you meant the stock ones (but I lightened the regex search for custom emojis just in case). Anyway, this was a bit harder than I thought and there might be a more efficient way to make it work, but what I did was importing an emoji library, "demojize" the text clean_content (turning emojis to how they're formatted, like :emoji_code: this) and deleting it through a regex search.

Actually, my original goal was to display the emojis normally as you said with their :emoji_code:, but I noticed that doing so "breaks" messages in multiple parts and forcibly adds a space after each ":" (example below)

https://user-images.githubusercontent.com/40474557/113036165-3c6e9700-9194-11eb-88d0-105fb58ae122.mp4

![image](https://user-images.githubusercontent.com/40474557/113036357-7770ca80-9194-11eb-8717-4dd365ad62f9.png)

Also, just an opinion but I feel like removing them actually improves the overall result? The sprites themselves convey enough emotion and they just feel out of place in the text box imo. That's your call though if you disagree.

2021-03-30 21:31 UTC, LuisMayo commented
Hi.

Yes, I didn't realize that that using the emoji_code would trigger the sentence detection when rendering the video due to the colon, you're right.

Not showing them seems a good idea. As you've said, the video has its own way of showing emotions so emojis may not work well. Removing them is an idea I like.

Eventually I'd like to move the emoji removal logic to ace-attorney-bot since the emojis may be deleted in all platforms, not only in discord.

But in the meantime it's ok doing it here

Thanks a lot!

2021-03-30 21:32 UTC, LuisMayo approved these changes

2021-03-30 21:34 UTC, merged